version: "3.9"
services:
  service-registry:
    image: service-registry:latest
    ports:
      - "8761:8761"
  account-service:
    image: account-service:latest
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
    ports:
      - "8081:8080"
    depends_on:
      - service-registry
  inventory-service:
    image: inventory-service:latest
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
    ports:
      - "8082:8080"
    depends_on:
      - service-registry
  lending-service:
    image: lending-service:latest
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
    ports:
      - "8083:8080"
    depends_on:
      - service-registry
      - account-service
      - inventory-service
    